// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqVGBX0_tGLdWJ-GI9e6d_PzWuqMswR78',
    appId: '1:623462495481:web:ebc1738c6e8f3afc36de28',
    messagingSenderId: '623462495481',
    projectId: 'colleage-3996e',
    authDomain: 'colleage-3996e.firebaseapp.com',
    storageBucket: 'colleage-3996e.appspot.com',
    measurementId: 'G-L8ESCHBP76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcRAup0wTiVT5b-27hXrXD1ilCxBEbFRY',
    appId: '1:623462495481:android:32fc88e3d8e425e536de28',
    messagingSenderId: '623462495481',
    projectId: 'colleage-3996e',
    storageBucket: 'colleage-3996e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP0b47rXciwzYCErODfsfV1PGF_zWkKCo',
    appId: '1:623462495481:ios:d80278692b07df1936de28',
    messagingSenderId: '623462495481',
    projectId: 'colleage-3996e',
    storageBucket: 'colleage-3996e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP0b47rXciwzYCErODfsfV1PGF_zWkKCo',
    appId: '1:623462495481:ios:d80278692b07df1936de28',
    messagingSenderId: '623462495481',
    projectId: 'colleage-3996e',
    storageBucket: 'colleage-3996e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqVGBX0_tGLdWJ-GI9e6d_PzWuqMswR78',
    appId: '1:623462495481:web:01a4c7dba012428436de28',
    messagingSenderId: '623462495481',
    projectId: 'colleage-3996e',
    authDomain: 'colleage-3996e.firebaseapp.com',
    storageBucket: 'colleage-3996e.appspot.com',
    measurementId: 'G-ZGM88RTHZ9',
  );
}
